### PR TITLE
Fix pyconfig missing when building boost

### PR DESCRIPTION
**Pull request by pwhelan**
I'm basically reopening an old PR, #235. This is one of 3 fixes necessary for building with docker.

### CODE REVIEW

**Comment by dhwz** [comment]
I think this change is not necessary, boost is building properly after changing the URL see my new PR

**Comment by pwhelan** [comment]
I will close this PR as soon as #345 is approved since I can confirm that it does fix the issue I was attempting to fix here.

**Comment by dhwz** [comment]
I think that can be closed now?

**Comment by pwhelan** [comment]
> I think that can be closed now?

I'll test it today then close it once I'm sure it's fixed the error. Just want to make sure this one stays fixed.

**Comment by pwhelan** [comment]
I tested a build yesterday straight from main with the boost upgrade/fix applied and I still got the same build error with boost. Can anyone else check this out with the docker build?

**Comment by dhwz** [comment]
and your fix doesn't help?

**Comment by pwhelan** [comment]
> and your fix doesn't help?

My fix does help but it works by changing a reference to the $SYSROOT_PREFIX environment variable top $TOOLCHAINS. I don't like the fix since I basically just changed the variable used to get it to work without knowing the full context of either variable.

**Review by dhwz — APPROVED** [review]
I thought a bit about the change and came to the conclusion that it is probably ok.

**Review by Cebion — APPROVED** [review]
No Building errors, evaluation from dhwz is pass.

**Pull request merged**
