### PR TITLE
M/P/V fixes

### PR DESCRIPTION
**Pull request by fewtarius**
* Correct scaling for vic-20 and vectrex
* Remove redundant rfkill statements (connman already takes care of this)

### CODE REVIEW

**Comment by szalik-rg351** [comment]
git fetch origin pull/265/head:265
git checkout 265
make world                                                

oh wait i have no approve anymore 🗡️

**Review by Cebion — APPROVED** [review]

**Comment by fewtarius** [comment]
Merging early as there's an update bug that needs fixing before things break.

**Comment by fewtarius** [comment]
If anyone has installed this update, after the re-issue they can ssh into the device and run:
```
bash -c "$(curl -fsSL "https://raw.githubusercontent.com/351ELEC/351ELEC/main/packages/351elec/sources/scripts/351elec-upgrade")"
```

This will fetch the latest version of the update script, and run the update.

**Comment by szalik-rg351** [comment]
image
seems like there is no info about build anymore

**Comment by fewtarius** [comment]
> image
> seems like there is no info about build anymore

Huh, wonder what happened.  I'll check it out.

**Comment by fewtarius** [comment]
Looks like the message payload was ok.

```
{"username": "Build Bot","content": "Build v2.0 (f7fa03c, main branch) is now available for installation.\n\nDownload from https://updates.351elec.org/releases/daily or update using the daily channel on your RG351P/M\n\nCommits since last build:\n\n```f7fa03ce Merge pull request #265 from 351ELEC/fixes\n110f6d8f Fix update script bug\nb0cf3841 Merge pull request #264 from ErikLentz/main\n452e5afb Fix scaling for vectrex and vic-20\n60d12c4e Remove rfkill, connman does this automatically so it's redundant\ndca282ea Updated link to the Wiki\n```"}
```

**Comment by szalik-rg351** [comment]
yeah its fixed now 
image

**Comment by szalik-rg351** [comment]
@fewtarius one more thing, cuse im trying to locate with user why he have issues with playing games/sounds and other ppl not and here is results 
image

**Comment by fewtarius** [comment]
> yeah its fixed now
> image

Nothing changed, it was probably just a glitch in the matrix.  We should stop using our PR comments for tech support and discord spill-over like this.  PR comments should be limited to PR activities.

**Comment by szalik-rg351** [comment]
okay but how i can send you info of something bad when you are not on discord?
everyone reports that sd2 give them no sound and controlls, and sd1 works fine. If you can back issue tracker i can do it here

**Comment by fewtarius** [comment]
> okay but how i can send you info of something bad when you are not on discord?
> everyone reports that sd2 give them no sound and controlls, and sd1 works fine. If you can back issue tracker i can do it here

I don't need to know about every glitch in the matrix.  This distribution is community supported, not just "Fewtarius" supported. :)

**Comment by szalik-rg351** [comment]
yeah yeah i understand but i thinked it might break by your side or something, 
image
here is maybe something helpfull with sd2

> sudo mount -o umask=0022,gid=1000,uid=1000 /dev/mmcblk1p1 /roms

**Comment by fewtarius** [comment]
These are corrected in #266.  When you attempt to use the Anbernic SD card in slot 2, it is FAT which breaks our game data partition since you can't symlink to a FAT volume.  NTFS support is missing in init so I was mistaken when I mentioned that it was supported.  There may be a missing WIFI on startup issue can be corrected by re-selecting the SSID.  That is also fixed.

"by my side" is meaningless in a community support model.   We merged the 351V PR before it was ready.

**Comment by szalik-rg351** [comment]
yeah truth about the PR i pull it to quick, lesson learned. 

However "by your side" i was mean problem with machine or something like that : ) thank you

thanks for sorting the issues quickly

**Pull request merged**
