### PR TITLE
Multiple updates and 351V support.

### PR DESCRIPTION
**Pull request by fewtarius**
Thanks to the release of source code by Anbernic, I'm happy to note that we are able to add support for the RG351V to 351ELEC.  This PR includes this support, and also updates RetroArch along with most emulators and cores.

Notes about the 351V:

* You can use the primary or secondary microsd card slot for games.  If you're using the second slot, it will take priority allowing a smaller SD to be used for the OS.  The GAMES partition should support FAT, EXFAT, NTFS, and EXT4 and must be partition 1.
* Autobuilds have been added for the 351V and can be found in the same location as the updates for the 351P/M once merged.
* Themes and packages may need updates to support this model, not sure if we'll add those yet.
* There may be bugs, we'll rely on the community to continue to refine support for the V as we do the P and M.
* make world continues to be the method to build world, however you can now make RG351P or make RG351V for single device support.  "make world" will build both, and needs double the storage as previous.

PR build is uploading and will be available at the URL below when complete.

https://updates.351elec.org/releases/pr/262

### CODE REVIEW

**Review by szalik-rg351 — APPROVED** [review]

**Review by Cebion — APPROVED** [review]
Madlad! How did you know that most of us ordered the 351V.
We already lost the hope with the new device since shanti had no plans to support emuelec 4.0 on the V and now we're back on track.

Thanks for this surprise!

**Comment by fewtarius** [comment]
> Madlad! How did you know that most of us ordered the 351V.
> We already lost the hope with the new device since shanti had no plans to support emuelec 4.0 on the V and now we're back on track.
> 
> Thanks for this surprise!

I figured since they opened the sources, we should reconsider our position. :)

**Comment by szalik-rg351** [comment]
Thanks Doc 🗡️

**Comment by szalik-rg351** [comment]
fun fact, i was watching this, when PR arrived: D
image

**Comment by fewtarius** [comment]
Since we've merged already we probably don't need the PR build, but I'll let it complete.  We probably merged a little early, but that's probably ok as I've been testing on both of my devices for a bit now.

**Comment by szalik-rg351** [comment]
@fewtarius  Can you just make simply c/p of the themes/packages and name the existing ones themes rg351m/p and make duplicate with rg351v? im not gonna make like crazy amount of themes but i will give it a shot for couple. And maybe Cebion will repack essential like Drastic

**Comment by fewtarius** [comment]
> @fewtarius Can you just make simply c/p of the themes/packages and name the existing ones themes rg351m/p and make duplicate with rg351v? im not gonna make like crazy amount of themes but i will give it a shot for couple. And maybe Cebion will repack essential like Drastic

We'll probably create device folders and move them there.  It will take a bit of work, I won't be able to get to it today.  I will say that the default theme looks pretty good as-is. :)

**Comment by szalik-rg351** [comment]
@fewtarius  Truth, but it can look always better : ) 
I still have psds, and some helpfull files to rework some essential themes for this, so I can give it a shot
thank you

**Comment by fewtarius** [comment]
FYI - WIFI is not yet working on the V

**Comment by szalik-rg351** [comment]
@fewtarius FYI - we got report that sound and controlls not work ( snes ). I edited video straight to the point and uploaded you here: https://www.youtube.com/watch?v=DfIzQZEdYQA

**Comment by fewtarius** [comment]
> @fewtarius FYI - we got report that sound and controlls not work ( snes ). I edited video straight to the point and uploaded you here: https://www.youtube.com/watch?v=DfIzQZEdYQA

Sound and SNES both work fine, and were tested before and after the PR image was uploaded.  There is probably something else going on there.  The only known issue was WIFI not being enabled which has been resolved and will be in the general daily build when it completes.  A factory reset, or removing the game data partition may correct any localized issue.

**Comment by szalik-rg351** [comment]
@fewtarius

" if you guys haven't figure out the no audio issue yet:

HP_ON='(SW_HEADPHONE_INSERT) 0'
HP_OFF='(SW_HEADPHONE_INSERT)* 1*'"

**Comment by szalik-rg351** [comment]
"its another thing that anbernic change for no reason"

**Comment by fewtarius** [comment]
> @fewtarius
> 
> " if you guys haven't figure out the no audio issue yet:
> 
> HP_ON='(SW_HEADPHONE_INSERT) 0'
> HP_OFF='(SW_HEADPHONE_INSERT)* 1*'"

```
https://github.com/351ELEC/351ELEC/blob/main/projects/Rockchip/devices/RG351V/packages/odroidgoa-utils/sources/headphone_sense.sh#L21
```

It is correct in the code, and in the RG351V image.

```
~ # evtest /dev/input/event1
Input driver version is 1.0.1
Input device ID: bus 0x0 vendor 0x0 product 0x0 version 0x0
Input device name: "rockchip,rk817-codec Headphones"
Supported events:
  Event type 0 (EV_SYN)
  Event type 5 (EV_SW)
    Event code 2 (SW_HEADPHONE_INSERT) state 1 <- No headphones
Properties:
Testing ... (interrupt to exit)
Event: time 1617646971.265515, type 5 (EV_SW), code 2 (SW_HEADPHONE_INSERT), value 0 <- Headphones
Event: time 1617646971.265515, -------------- SYN_REPORT ------------
Event: time 1617646973.589423, type 5 (EV_SW), code 2 (SW_HEADPHONE_INSERT), value 1 <- No headphones
Event: time 1617646973.589423, -------------- SYN_REPORT ------------
Event: time 1617646975.161496, type 5 (EV_SW), code 2 (SW_HEADPHONE_INSERT), value 0 <- Headphones
Event: time 1617646975.161496, -------------- SYN_REPORT ------------
Event: time 1617646977.361474, type 5 (EV_SW), code 2 (SW_HEADPHONE_INSERT), value 1 <- No headphones
Event: time 1617646977.361474, -------------- SYN_REPORT ------------
```

**Pull request merged**
