### PR TITLE
Add EpicBlancheNoir to themes.cfg

### PR DESCRIPTION
**Pull request by kefren68**
A Black & White ES theme for 351ELEC

### CODE REVIEW

**Comment by anthonycaccese** [comment]
Thank you for submitting this @kefren68.   Will look this evening to test that the firmware still builds with this change.  It should be fine as your update is straightforward - but just want to check just in case.   

Also, our theme downloader allows for a preview of each theme.  If you want to provide a preview image of your theme you can do so by creating a 300x200 jpg named the same as the name you submitted in themes.cfg

So in your case you could provide a JPG named "351ELEC-EpicBlancheNoir.jpg"

The folder it would go into is "351ELEC/metadata/themes/"

**Comment by kefren68** [comment]
Thank you very much.
I've added the preview image.

**Comment by anthonycaccese** [comment]
Awesome! thank you.  You should be able to submit the image as a part of this PR as well so we can include it all at the same time.

**Comment by anthonycaccese** [comment]
tested and working in a local build

**Comment by anthonycaccese** [comment]
@kefren68 please submit a PR for the image preview when you have a moment

**Pull request merged**
