### PR TITLE
Alternative ArtBook Theme: Alt-Book

### PR DESCRIPTION
**Pull request by bebeidon**
Fullscreen Backgrounds

### CODE REVIEW

**Comment by anthonycaccese** [comment]
@bebeidon for the preview image try adding it to your repo in this folder "/metadata/themes" and name it Alt-Book.jpg.  You may be able to submit that along with this PR 

@szalik-rg351 when you get a moment can you help test this one?

Thank you!

**Comment by bebeidon** [comment]
ok i think i did

**Review by fewtarius — APPROVED** [review]

**Comment by szalik-rg351** [comment]
its fine, but can you put it lower on the list? Its basicly same looking theme as artbook, we like to get it in, but just find some better spot for it if you can :)

**Comment by fewtarius** [comment]
I'm not fond of pushing themes out of order because they're similar, instead maybe we should sort the list alphabetically?

**Comment by szalik-rg351** [comment]
@fewtarius this can be an option too, i just sorted them in order with ones cost most of the work and with ones looks best for now

**Pull request closed without merging**
