### PR TITLE
041021-updates

### PR DESCRIPTION
**Pull request by fewtarius**
This PR updates RetroArch, cores and emulators.  It also fixes a file manager resolution bug on the RG351V and re-adds some basic metadata for users who have not updated.  It is tested to build and the few cores and emulators that I tested worked fine.

### Bug Fixes
* File Manager resolution on RG351V.

### Distribution Updates
* Rework the package update script to support updating emulators, and block certain packages that are known to not work after updating.
  * To use, change into the project root and run ./scripts/update_packages.
* Add "empty" package and theme metadata instructing users to update to daily builds.
* Enable Sync to Exact Content Framerate in RetroArch (for new installs), as it seems to smooth scrolling on the RG351V.
* Set the screenshot directory to the games partition and create the directory if it doesn't exist.
* If the user formats the games partition on sd1 or sd2 it will be re-populated from our read only templates on startup.  This corrects an issue with lack of controls after users add a second microsd.

### Package Updates
* RetroArch, Overlays, Assets, DB, Core Info
* PPSSPPSDL
* amiberry
* hatarisa
* mupen64plus-nx
* openbor
* reicastsa
* scummvmsa
* TIC-80
* atari800
* beetle-pce
* beetle-pcfx
* beetle-supergrafx
* beetle-vb
* beetle-wswan
* bluemsx
* dinothawr
* dosbox-svn
* duckstation
* fbalpha2012
* fbneo
* fceumm
* flycast
* fuse
* gpsp
* mame2003-plus
* neocd_libretro
* ppsspp
* puae
* stella
* tyrquake
* vice

### CODE REVIEW

**Comment by anthonycaccese** [comment]
Looking good so far from initial review. 

I see this removes residualVM as specific emulator.  Safe to say thats because of the updates we made to ScummVM that enable Residual games there?

I noted you added sha256 to scummvmsa package.mk.  Should I make sure to add that going forward if there are new updates we want to bring in?

**Comment by fewtarius** [comment]
> Looking good so far from initial review.
> 
> I see this removes residualVM as specific emulator. Safe to say thats because of the updates we made to ScummVM that enable Residual games there? Wondering if there are other places to remove this like maybe "/games" folder creation for new installs?
> 

The update didn't build and I thought since we just updated scummvmsa it was safe to deprecate it.  If we still need it, I can re-add.

> I noted you added sha256 to scummvmsa package.mk. Should I make sure to add that going forward if there are new updates we want to bring in?

Normally we do want to include the SHA256 sum, but I updated everything with a script it does it automatically.  I didn't specifically add it because it was missed or anything. :)

**Comment by anthonycaccese** [comment]
👍 building locally now to test things tonight

**Comment by Cebion** [comment]
Sounds good, still building here.

**Comment by anthonycaccese** [comment]
It built ok on my end and I am running the image on my RG351P test card
OS BuildID: 69dbe15

**Working:**
- ScummVM (tested monkey, grim and geminirue)
- NES (balloon fight)
- SegaCD (sonic cd)
- SNES (pilotwings and super mario rpg)
- TGCD (dracula x)
- GB (balloon kid)
- GBA (final fight)
- PSP (final fantasy III) 
- EasyRPG (ara fell)
- RetroAchievements (tested in snes, nes and tgcd)

**Not working:**
- Daphne
  - This looks like a regression from OS buildID 464d0d0
  - Trying to boot Dragon's Lair just falls back to the gamelist
  - I checked my real card and confirmed that it works and boots correctly on OS BuildID 464d0d0.
  - Its odd because I don't see any hypseus changes in this commit or the other PRs since that buildID

** Other Notes:**
- DosBox - I don't have any games on my test card to work with but I know @Cebion you may have some 😄
- RetroAchievements icons are showing up as faded icons in the ES menu for all of my systems.  I thought this was fixed in a previous commit but not sure of the details.  That said, it doesn't break functionality so I think its good to move forward as this may be related to something else.

**Review by anthonycaccese — APPROVED** [review]

**Comment by fewtarius** [comment]
I've added another RG351V bug fix that I've tested locally.  This one will populate the gamedata directory on startup if the user changes the microsd slot 2 or formats the games partition on sd1.

**Comment by fewtarius** [comment]
@Cebion anything we need to take another look at with this PR?

**Review by Cebion — APPROVED** [review]
Looks good.m, no issues on my end.

**Comment by mtoensing** [comment]
This fixed #302

**Pull request merged**
