### PR TITLE
Update duckstation

### PR DESCRIPTION
**Pull request by bradbajuz**
[Duckstation](https://github.com/libretro/duckstation) has finally been updated on libretro since being months behind stenzek:master.

### CODE REVIEW

**Review by fewtarius — APPROVED** [review]
This looks fine, we'll just need to test build.  I'll try and make time when I can.

**Review by szalik-rg351 — APPROVED** [review]

**Comment by fewtarius** [comment]
This PR was merged before testing, and it doesn't build.  Please test PRs before merging.

**Comment by szalik-rg351** [comment]
yeah sorry i just readed looks fine, didn't go to the rest of msg

**Comment by bradbajuz** [comment]
Sorry this didn't build.

Seeing that duckstation seems to be the only PSX emulator being updated and maintained on a regular basis, what's involved to get it to a point where it could eventually be the default PSX emulator in 351ELEC? libertro seems to have someone keeping their fork of it up to date now.

**Comment by fewtarius** [comment]
> Sorry this didn't build.
> 
> Seeing that duckstation seems to be the only PSX emulator being updated and maintained on a regular basis, what's involved to get it to a point where it could eventually be the default PSX emulator in 351ELEC? libertro seems to have someone keeping their fork of it up to date now.

It just won't build as-is and will take some additional work.  Unfortunately it was merged before we could determine what it will take to update the source to build on 351ELEC so I just rolled it back to stop the build from breaking.  When I have some additional time I'll work on getting it building correctly.

**Pull request merged**
