### PR TITLE
Fix PPSSPPSDL by bumping libpng up to 1.7.0beta89

### PR DESCRIPTION
**Pull request by pwhelan**
Getting PPSSPPSDL to compile with it's own version of png17 requires it to not be detected in the base system, which must require some kind of arcane magic or timing that doesn't occur when compiling in the docker image.

An alternative fix would be to patch PPSSPPSDL to ignore the base libpng install but this seemed to me to be the path of least resistance, especially since the libpng project is said to be poised to release a stable build of png 1.7 *ANY* *DAY* *NOW* (tm).

### CODE REVIEW

**Comment by dhwz** [comment]
That a 1.7 is anytime coming soon seems not to happen this beta is already 4 years old.

**Comment by pwhelan** [comment]
> That a 1.7 is anytime coming soon seems not to happen this beta is already 4 years old.

Then we'll have to add a patch to fork PPSSPPSDL to use it's own version of libpng17 or backport it to libpng16.

**Comment by dhwz** [comment]
Yes but can you explain me what exactly the problem is, as it builds just fine for me? It only not builds with Docker? But why?

**Comment by pwhelan** [comment]
most likely due to some bizarre timing problem or path or something else that occurs in ubuntu when running the build outside of docker. I haven't gotten to the the bottom of it. I'll do another build and copy/pate the log of the build failure soon.

**Comment by dhwz** [comment]
I'm closing this in favor of #367

**Pull request closed without merging**
