### PR TITLE
Theme updates

### PR DESCRIPTION
**Pull request by szalik-rg351**
So now we have 22 total :)

Recon is no longer active so temporary his fork of carbon is removed.

### CODE REVIEW

**Review by Cebion — APPROVED** [review]
Awesome work!

**Comment by anthonycaccese** [comment]
So awesome. Cheers @szalik-rg351

**Comment by fewtarius** [comment]
This PR broke build dependencies causing the build to fail, it will need to be corrected.

`Traceback (most recent call last):
  File "scripts/genbuildplan.py", line 364, in <module>
    REQUIRED_PKGS = processPackages(args, ALL_PACKAGES, args.build)
  File "scripts/genbuildplan.py", line 290, in processPackages
    raise Exception(msg)
Exception: Invalid package reference: dependency es-theme-handheld-simple in package 351elec-emulationstation::PKG_DEPENDS_TARGET is not valid
Parallel build failure - see log for details. Time of failure: Sat Mar 27 23:00:05 EDT 2021
make[1]: *** [Makefile:12: image] Error 1`

**Comment by anthonycaccese** [comment]
Caused by the removal of handheld simple.  I’ll fix now. FYI @szalik-rg351 for future updates

**Comment by fewtarius** [comment]
Yeah.  We can test build pull requests by checking them out locally into our existing build root.  For example:

```
git fetch origin pull/252/head:252
git checkout 252
make world
```

After testing, you can just checkout main again and delete the local branch.

**Comment by anthonycaccese** [comment]
testing now

**Pull request merged**
