### PR TITLE
Added .m3u extension to AMIGA

### PR DESCRIPTION
**Pull request by XargonWan**

### CODE REVIEW

**Comment by fewtarius** [comment]
This PR should not target the main branch, please update it to push from your 2.1 branch to our 2.1 branch.

**Review by fewtarius — CHANGES_REQUESTED** [review]
Will approve once it targets the correct branch.

**Comment by Cebion** [comment]
Uhm, since when do we have a 2.1 branch?

image

**Comment by fewtarius** [comment]
This PR had an unresolved merge conflict and needs to be resubmitted so it can be merged cleanly.  You can ignore the 2.1 branch stuff, that's just how long this has been open waiting to be fixed.

**Pull request closed without merging**
