### PR TITLE
Adds RetroRun emulator and flycast32_rumble core to improve performance of dreamcast, naomi and atomiswave emulation

### PR DESCRIPTION
**Pull request by navy1978**
Adds RetroRun emulator and flycast32_rumble core. 

Supported platforms are:
dreamcast
naomi
atomiswave

### CODE REVIEW

**Comment by szalik-rg351** [comment]
thank you for doing this for us <3

**Comment by anthonycaccese** [comment]
I'll do a build and test of this this weekend

**Comment by anthonycaccese** [comment]
Updates so far:
Builds locally for both RG351P/V firmwares
Unable yet to test that download package is working from package downlader - I have asked for help in discord.

**Review by anthonycaccese — APPROVED** [review]
Finished testing end to end and the changes look good.

I was able to install the package, change my default emulator for Dreamcast and test a few games.

Looks good to me.

**Review by Cebion — APPROVED** [review]
Build fine, tested, awesome!

**Pull request merged**
