### PR TITLE
Cleanup ES Settings/Defaults for disc-based-systems

### PR DESCRIPTION
**Pull request by konsumschaf**
For disc-based-systems:

* delete .zip/.7z 
* hide .iso, .bin, .img, .toc by default

**Note**: does only take effect for new installations, factory resets and if you copy over the es_settings.cfg and es_systems.cfg manually.

### CODE REVIEW

**Comment by szalik-rg351** [comment]
is that mean i have to generate all of the cue for psx games, or this will be a toggle option 📦

**Comment by Cebion** [comment]
> is that mean i have to generate all of the cue for psx games, or this will be a toggle option 📦

You should never load bin files directly in psx

**Review by Cebion — APPROVED** [review]
Built fine,

**Review by Cebion — APPROVED** [review]
Looks good, reflects the changes we talked about.

**Comment by szalik-rg351** [comment]
> > is that mean i have to generate all of the cue for psx games, or this will be a toggle option 📦
> 
> You should never load bin files directly in psx

they work fine, so why :D?

**Review by Cebion — APPROVED** [review]
Looks fine, built okay!

**Comment by anthonycaccese** [comment]
@szalik-rg351 regarding your questions...

"is that mean i have to generate all of the cue for psx games, or this will be a toggle option" - This will allow you to toggle on the display of .bins if you need to use those still.  It just hides them by default as the cleanest way to set up games in this way is with .cue/.bin.  This helps resolve one of most asked questions by our community of "why do i see duplicate entries for my games" while still providing the flexibility to turn back on certain extensions if you need to.  Essentially it makes it a cleaner out of the box experience. 

also of note - in order for this to take affect for you please check out @konsumschaf note... "only takes effect for new installations, factory resets and if you copy over the es_settings.cfg and es_systems.cfg manually."  So if you don't plan to do any of those you won't have to change anything about your set up.

**Comment by anthonycaccese** [comment]
confirmed builds well and game lists display as expected with this change.  Also still retains the ability to turn on extensions that have been hidden so users have that option if they need.

**Review by anthonycaccese — APPROVED** [review]

**Pull request merged**
