### PR TITLE
Patch for LCD streak issue

### PR DESCRIPTION
**Pull request by YonKuma**
Implementation of the magical fix for screen issues for the 351V.

I've tested to make sure it doesn't interfere with booting on the V or M, seems fine in that respect. I don't have a console with the problem to confirm that this fix does anything though.

### CODE REVIEW

**Comment by usersaurus** [comment]
If the streak issue is this one...

image

...I can test it.

Is the build available somewhere or should I checkout the branch and build it myself?

**Comment by dhwz** [comment]
You can download it here
https://github.com/351ELEC/351ELEC/pull/585/checks?check_run_id=3256752217

**Comment by YonKuma** [comment]
@usersaurus That would be incredibly helpful. If you follow the link dhwz put in, you can click on Artifacts > RG351V-PR-585-screenpatch to download it.

**Comment by usersaurus** [comment]
Already said it in the discord channel, but...
The fix works like a charm. After 2 hours no lines so far.

**Comment by usersaurus** [comment]
Tested without OC during one hour and a half. No lines 🙌, so in my case the problem is completely fixed.

**Comment by CloudDweller** [comment]
Can someone please explain how to install the fix? I've download the tar file but when I expand the archive I don't have an image, so I'm not sure how to install this on a clean SD card.

**Comment by usersaurus** [comment]
@CloudDweller are you currently using 351elec? If that's the case:
- download
- decompress the file
- move the tar file to storage/roms/update

**Comment by CloudDweller** [comment]
> @CloudDweller are you currently using 351elec? If that's the case:
> 
> * download
> * decompress the file
> * move the tar file to storage/roms/update

Perfect! Thanks. I'm a little new to the 351ELE scene so I appreciate the help :)

**Review by pkegg — APPROVED** [review]
Didn’t test, but multiple confirmed good tests and LGTM

**Review by dhwz — APPROVED** [review]

**Comment by edneicabofrio** [comment]
foto1
Foto2
Foto3

Videos:  
https://youtu.be/I2L1SIOjC8E
https://youtu.be/9tN06xjqrTc

Hello colleagues,

I purchased my RG351V from banggood.com.
As you can see in the pictures above, my console is having problems with black lines at the bottom of the screen. The top part is also reproduced at the bottom of the screen.
This issue occurs when I play the console for a few minutes long enough for it to be warm.

I tried several versions of emuelec, 351ELEC and now I'm using ARKOS but the problem persists.

This indicates that it is a hardware issue and so I have filed a dispute with banggoo.com to resolve the issue.

I will try this solution.

Thanks in advance.

Ednei

**Pull request merged**
