### PR TITLE
040621 fixes

### PR DESCRIPTION
**Pull request by fewtarius**
* Remove NTFS and FAT32 from the supported list.
  * EXFAT and EXT4 are the only supported filesystems, NTFS may be added in the future.
* Correct autostart to not enable WIFI as it's already enabled.
* Update autostart to disable WIFI if it's disabled in ES to soft block the radio.
* Fix the boot automount to try and mount formatted volumes that don't have a primary partition which is the default in Windows.

### CODE REVIEW

**Review by Cebion — APPROVED** [review]

**Comment by fewtarius** [comment]
I should also mention that in this PR is the theme/package split to metadata/device/

**Comment by szalik-rg351** [comment]
FPRI - one community member made a build and confirm that wi-fi issue is fixed 
image

**Comment by fewtarius** [comment]
> FPRI - one community member made a build and confirm that wi-fi issue is fixed
> image

Great, there are a few more things to do before this can be merged.

**Comment by fewtarius** [comment]
I've enabled GitHub discussions as a space for the community to interact with the project.

**Comment by fewtarius** [comment]
@Cebion @szalik-rg351 @anthonycaccese the package and theme separation is implemented, and the images are uploaded.  It's a breaking change until everyone updates, and then things work normally again.  The daily builds with these changes have finished uploading.

**Comment by anthonycaccese** [comment]
sounds good @fewtarius.  Would this be accurate to say about the breaking change?...

---

Hi Everyone,

With the work that has been occurring to enable a version of 351ELEC for the RG351V its required a few changes that will break things for all of us using existing builds.  

Specifically it will break these 2 things:
- If you try to download themes from "Menu > Updates & Downloads > Themes" you will see a blank screen
- If you try to download packages from "Menu > Updates & Downloads > Packages" you will see a blank screen

This is because we needed to create a separation between themes/packages between MP and V models of the device.  Primarily because of the aspect ratio difference from 3:2 (MP) to 4:3 (V).  The benefit of this is it will allow the community to create themes and packages specifically tailored for a given screen resolution.  And as a user it means you will be able to download things that are know to work with the aspect ratio of your device.  

What is the fix?
- Update to the next daily build once it is released.
- After that update the download lists for themes and packages will display content again.

**Comment by fewtarius** [comment]
Yes, that's perfect.  The update is also available now.  I finished installing it on my devices a few hours ago. :)

**Comment by fewtarius** [comment]
I'm going to swipe this and add it as a discussion. :)

**Pull request merged**
