### PR TITLE
Update distribution.conf

### PR DESCRIPTION
**Pull request by acridAxid**
Fixed alphabetical sort of options.

Removed some old `#TODO:` notes I left here.

Disabled `autosave` for `mame` and `arcade` systems (MAME core is an optional core for this system), as MAME save states are not universally working; one user reported being stuck in a bad state and needing to manually purge the state file to recover.

Removed `maxperf` parameter for `arcade` and `mame`; most games don't need it and users can enable if they want it.

### CODE REVIEW

**Comment by dhwz** [comment]
Sorry but we will not remove support for separated japanes systems please restore megadrive japan

**Comment by acridAxid** [comment]
> Sorry but we will not remove support for separated japanes systems please restore megadrive japan

Pushed the wrong commit to this, fixing..

**Comment by acridAxid** [comment]
Fixed, safe to review now.

**Comment by acridAxid** [comment]
Broke this with a bad push, will re-submit.

**Pull request closed without merging**
