### PR TITLE
Revert adding epicblanchenoir

### PR DESCRIPTION
**Pull request by szalik-rg351**
This theme simply just swap the graphics from epic-noir to be black and white without adjusting it to rg351p aspect ratio. Many systems are missing and some of them have a bad names.  This theme should be consider as a WIP, instead of adding it to package as a ready to use one

### CODE REVIEW

**Comment by anthonycaccese** [comment]
I think its better to reach out to the author of this theme and make suggestions for improvement.  They look to have all the core systems in place that would cover most users use cases.  I think its ideal that a theme supports all of 351Elec systems I woudn't say its a requirement.

**Comment by szalik-rg351** [comment]
Someone already tryed to contact him without response. I don't think we should go into quantity when we promise quality " Now, no matter which theme you choose you no longer have to worry if its going to fit the screen well or if its going to be too large to download.  Just simply pick the one you like the best." :) And as i said this theme is not much different that the ones we have already and they are optimized. So we should wait before he optimize and raise it to our standards we set, before adding it...

**Comment by szalik-rg351** [comment]
i made the issue
https://github.com/kefren68/es-theme-351ELEC-epicblanchenoir/issues/1

**Comment by anthonycaccese** [comment]
Awesome thank you, let’s revisit this PR after we hear back from them.

**Comment by kefren68** [comment]
Hi. i think szalik-rg351 is right.
I'm working to the theme to correct all the mistakes and to add the missing systems.
Right now is not ready...

**Comment by anthonycaccese** [comment]
@kefren68 no worries, would you like us to remove it from theme downloader for now and then you can make a new PR when you think it is ready?

**Comment by kefren68** [comment]
Yes, please.
I'll work on it in the next days and then iìll make a new PR.
Thank you for your help.

**Comment by anthonycaccese** [comment]
Thank you @kefren68.  See you on discord and looking forward to collaborating on updates.

**Pull request merged**
