### PR TITLE
Rewrite setsettings.sh in Python, bezels defaults and small fixes

### PR DESCRIPTION
**Pull request by konsumschaf**
* Re-write of setsettings.sh in Python
* explicit defaults for bezels
* bugfix in Emulationstation
* Enable Analog to Digital Type to left Analog

### CODE REVIEW

**Comment by pkegg** [comment]
FYI: Skimmed this and looks good.  I still want to sit down and test it - particularly the bezel stuff.  Last couple days have been crazy, but still on my radar to look at.

**Review by pkegg — APPROVED** [review]
This looks good to me.  As discussed offline, I think it would be good to figure out a way to make bezels work by default for people updating from Pineapple Forrest, but I can make that a separate PR.

**Comment by pkegg** [comment]
FYI - made a PR (https://github.com/351ELEC/351ELEC) which should make bezels upgrade cleanly and default to 'on'.

**Comment by konsumschaf** [comment]
Do not merge right now, more changes are coming. ;-) Need to push the ES changes first.

**Comment by konsumschaf** [comment]
Add _Integer Scale Overscale_ to the ES menu - will be useful for the 552. ;-)

**Comment by Zowayix** [comment]
Whoops! I didn't even notice this PR was here until now. I'd better take a look at this myself and probably nitpick it later after I've made sure it all works. Looks like it should?

**Comment by konsumschaf** [comment]
Keltron3030 will check if we still need to disable HC mode during netplay.

**Comment by konsumschaf** [comment]
Keltron3030 tested the change and everything is working.

**Comment by dhwz** [comment]
closed after manual merge

**Pull request closed without merging**
