### PR TITLE
New bezels by Raven Kilit and random bezels

### PR DESCRIPTION
**Pull request by konsumschaf**
* Support for random bezels added:
  * must follow this convention romname.1.cfg, romname.2.cfg, ...
* New bezels by Raven Kilit
  * Bezels without branding
  * Bezels with small logo
  * Bezels with large logo
* Pre-configured for GB/GBC
  * Tetris
  * Mario
  * Pokemon

### CODE REVIEW

**Review by dhwz — APPROVED** [review]

**Comment by konsumschaf** [comment]
* Removed logos
* Add enhanced .cfg to enable easy configuration of shadow and/or grid.
* Default system bezel has shadow and grid enabled (GB, GBC, GG only)

**Comment by konsumschaf** [comment]
Bugfix: Spaces in the path broke random bezels (thanks to @RavenKilit for finding this)

**Comment by konsumschaf** [comment]
* Add generate-bezel-cfg.sh to help generation bezel .cfg files

**Comment by konsumschaf** [comment]
Let's merge this - in the beta is an older version - not easy to debug.
Will clarify the perfect bezel with @szalik-rg351 and @RavenKilit as soon as they are both back.

**Review by pkegg — APPROVED** [review]
Agree this looks good enough to merge and we can continue to make improvements from there.

**Pull request merged**
