### PR TITLE
Updatefixes

### PR DESCRIPTION
**Pull request by fewtarius**
This PR will update the distribution to use a new version method replacing "2.0".  The new distribution version structure will be: "YYYYMMDD".  This will allow us to use GitHub releases for system updates and it pairs with the changes made to builder.

To implement, a build will be created and uploaded to the current web farm, and released as a GitHub release at the same time.  This will shift users to GitHub for the next update as they update from the web farm.  After a few days we will destroy the last remaining update.351elec.org instance.

When we are testing PRs we will need to switch to using the builder automation, otherwise the versions will not increment properly as it's incremented with automation.

### CODE REVIEW

**Comment by anthonycaccese** [comment]
Thank you fewt

Re: "When we are testing PRs we will need to switch to using the builder automation, otherwise the versions will not increment properly as it's incremented with automation."
For local builds how do we pass this to trigger the automation for testing purpose?

**Comment by Cebion** [comment]
Also curious, thanks for you work!

**Comment by fewtarius** [comment]
If you're just testing locally you could just build as you do, keeping in mind the version number will not be correct.  Alternately you can update LIBREELEC_VERSION in distributions/351ELEC/version to the YYYMMDD formatted date.  If you would like to test with the builder you can use that tool as well and it will increment it locally for you.  You'll need to edit the example to remove the notification and push parameters.

https://github.com/351ELEC/builder/blob/main/daily.example.sh

**Comment by fewtarius** [comment]
To test the update tools this morning, I ran a build and had builder push to a mirror repository, then I edited the URLs in the update scripts to use it.  The test upgrade completed successfully.

```
~ # ./updatecheck
20210418 DAILY
~ # ./351elec-upgrade
Sun Apr 18 07:40:07 EDT 2021: Network connection detected
Sun Apr 18 07:40:08 EDT 2021: Update available 20210418 > 20210416
Sun Apr 18 07:40:08 EDT 2021: Fetching 351ELEC-RG351P.aarch64-20210418.tar from https://github.com/fewtarius/351ELEC/releases/download/20210418
Sun Apr 18 07:42:17 EDT 2021: Verifying 351ELEC-RG351P.aarch64-20210418.tar
Sun Apr 18 07:42:51 EDT 2021: Syncing...
Sun Apr 18 07:42:52 EDT 2021: rebooting..
```

**Comment by fewtarius** [comment]
The builder examples now show a weekly clean full and daily incremental builds.

https://github.com/351ELEC/builder

This PR is ready to merge once approved.

**Comment by fewtarius** [comment]
I've added an example for doing local builds.  It will accept the branch as a parameter.  If you pass a numeric branch id, it will assume a PR build.

Once the scripts have been edited and renamed, they can be used to build this PR.

```
cd ~/351ELEC
../../builder/world
../../builder/local 328
```

https://github.com/351ELEC/builder/blob/main/local.example.sh

**Comment by anthonycaccese** [comment]
Sorry my delay on review of this one.  I am planning for time this weekend.

**Pull request merged**
