### PR TITLE
Add screenscraper support for pico-8 and extended support for cheevos…

### PR DESCRIPTION
**Pull request by konsumschaf**
… leaderboards

* Add screenscraper support for pico-8
* Add extended support for retroachievements leaderboards
* Points to my ES repo until https://github.com/351ELEC/351elec-emulationstation/pull/24 is merged

### CODE REVIEW

**Comment by dhwz** [comment]
Please don't push commits with your private repositories.

**Comment by pkegg** [comment]
This looks good - but I think it needs to deal with what happens if a user has the old default setting (`global.retroachievements.leaderboards=0`).

After updating to this, my emulationstation crashes and nothing is saved when exiting `Games -> Retroacheivment Settings` until I switch 'Leaderboards' from the weird 'unknown' character to 'DISABLED'.  Then everything seems to work fine.

I'm not an ES expert, but I think something like adding a check for "0" here and mapping to `disabled` (and probably mapping "1" to `enabled`)  here would do it: https://github.com/351ELEC/351elec-emulationstation/blob/6f220fd905cca6dc86da5914b9aabbba3d4502ca/es-app/src/guis/GuiMenu.cpp#L1916

**Comment by konsumschaf** [comment]
> This looks good - but I think it needs to deal with what happens if a user has the old default setting (`global.retroachievements.leaderboards=0`).
> 
> After updating to this, my emulationstation crashes and nothing is saved when exiting `Games -> Retroacheivment Settings` until I switch 'Leaderboards' from the weird 'unknown' character to 'DISABLED'. Then everything seems to work fine.
> 
> I'm not an ES expert, but I think something like adding a check for "0" here and mapping to `disabled` (and probably mapping "1" to `enabled`) here would do it: https://github.com/351ELEC/351elec-emulationstation/blob/6f220fd905cca6dc86da5914b9aabbba3d4502ca/es-app/src/guis/GuiMenu.cpp#L1916

Can reproduce and will fix this in `postupdate.sh` - Thanks for finding this! :pray:

**Comment by konsumschaf** [comment]
* Fixed ES crash with old settings in distribution.conf @pkegg please re-check
* Include latest emulationstation

**Review by pkegg — APPROVED** [review]
Tested this and it seems to work and also fixes the issue I raised.  LGTM!

**Review by dhwz — APPROVED** [review]

**Pull request merged**
