### PR TITLE
Automated m3u creator for psx

### PR DESCRIPTION
**Pull request by seajaysec**
Creating new tool for users to have an automated method of creating m3u files for their psx games.

### CODE REVIEW

**Comment by mtoensing** [comment]
@seajaysec Why generate a m3u file for every psx game? Just because you can hide cue and bin? Why not generate the .m3u and hide the specific bin and cues via the gamelist.xml.

**Review by fewtarius — CHANGES_REQUESTED** [review]

**Comment by Oxyur** [comment]
> 
> 
> @seajaysec Why generate a m3u file for every psx game? Just because you can hide cue and bin? Why not generate the .m3u and hide the specific bin and cues via the gamelist.xml.

I personally not edit gamelist.xml, because if you edit them and scrape, the scraper delete your modifications. I prefer the scraper to edit them, and if not detected that my games are read directly by the frontend.

When you scrape, the scraper will include every game which is read by the frontend. For a playstation, where you a have multiple data formats, (for example 15 data tracks for bust a move 2), AND some multiple discs, it can multiply by 4 the number of games scraped, which are false positives. This happens even if these files are hidden.
For my personnal collection, if I let every file read by default, I have 999 games.

I don't want to use compressed formats, it takes too long to open roms.

Only solution I've found to make a correct game list in 351ELEC for playstation : go in /storage/.config/emulationstation/es_systems.cfg, edit system psx, line extension, to make extensions .bin / .img / .iso not supported (delete them). Then the frontend will not try to scrape it, and my games boot from cue and m3u files.
My 999 games become... 249 games.

But we still have the problem with multiple discs & the cue files with it, which is unecessary for multiple cd games where you have a m3u, then make a lot of cue doublons "disc 1", "disc 2". Then I edit the same es_systems.cfg, and delete .cue. But, as the m3u is the last thing the frontend reads, I need it for every game, even one disc ones. This time the m3u will only point to an unique cue.

And this is what maybe answers your question : in my case at least, I absolutely need m3u for every playstation game, including the 1 disc roms that I have not now.

**Comment by szalik-rg351** [comment]
we still might work on this

**Review by seajaysec — COMMENTED** [review]
Agreed with fewt on all counts :)

**Comment by seajaysec** [comment]
I'll test out the message stream time and while/read searching on my device. Might be a few days though - slammed currently.

**Comment by mtoensing** [comment]
I feel it would be better not to spoil the party but isn't it easier to use .chd files with .m3u files for multi disc games and .cue/bin for the rest? That way you can hide .chd files and everything should work fine.

**Comment by sertiana** [comment]
> I feel it would be better not to spoil the party but isn't it easier to use .chd files with .m3u files for multi disc games and .cue/bin for the rest? That way you can hide .chd files and everything should work fine.

At least the m3u generator is not enforced. If you don't feel like using it then there is no need to do so.

**Pull request closed without merging**
