### PR TITLE
Build Optimization - remove version from build dirs - improve make clean

### PR DESCRIPTION
**Pull request by pkegg**
## Background
There are a couple issues making automated builds difficult this PR addresses. 
1. build version is encoded into the build directories (see below)
2. make clean removes `.ccache` - which means already built code must be fully recompiled after clean.

Currently, the build directories include the version.  For example, `build.351ELEC-RG351V.aarch64-20210603` where the version is `20210603`.

This means that when a new version is released, a fresh compile *must* be done.  Additionally, a `make clean` should be done to remove the old build directories (or you'll have ~140GB of unused files)

This is a minor inconvenience for developers, but for a build server that caches the `build.*` directories, it will either add complexity (needs to detect version change and `clean`) or instability (version change caues out of disk errors) if this issue is not fixed.

I believe @dhwz is in support of this change as per comments in discord.  dhwz may have additional files that need to be updated.

## Fix
The fix for `make clean` removing .ccache folder is to move .ccache to the project level.  This has the added benefit of compilation reuse between the P and V builds

The fix for build folder naming is just to remove the version from the `BUILD` variable (an example build folder would become:  `build.351ELEC-RG351V.aarch64`).  There are also few changes in packages to ensure they match the new format when copying files from another build folder.  

Ideally, this fix should go in before enabling automated builds.

I have manually tested a full RG351V build and it appeared to be working.

### CODE REVIEW

**Comment by pkegg** [comment]
FYI - If we were to also want to reuse .ccache after `make clean`.  We could switch to how CoreELEC does it (delete `build/*` which doesn't include .ccache): https://github.com/CoreELEC/CoreELEC/blob/coreelec-19/Makefile#L18 - I haven't included this change, but it's obviously easy to add.

**Comment by pkegg** [comment]
Updated PR to: 1. share .ccache across P and V builds.  2. Increase .ccache size to 20G as that is the equivalent size now that it is shared.

Running a build now - appears to be working well, but likely will take another 5 or so hours to run.  Will try and get some data around how long `make clean` takes after that optimization.

**Comment by pkegg** [comment]
Initial results look good. RG351V build took only about 22 minutes (instead of 2.5 hours) with the reused `.ccache`.  See: https://github.com/pkegg/351ELEC/runs/2750123605?check_suite_focus=true (FYI: the the real 'P' build time would have still been about 2.5 hours even though it shows 1.5 hours - I just had to restart it).

FYI: Trying a new build after `make clean` done manually on the server.  This will show how fast we can do a full build with the reused `.ccache` change.  Build is in progress here: https://github.com/pkegg/351ELEC/runs/2750634098?check_suite_focus=true

**Comment by pkegg** [comment]
So - run normally, it appears that time goes from 2.5 hours to ~55 minutes for RG351P.  The CPU usage is far less, so running concurrently buliding both P and V  (which might have issues with `.ccache`, but seemed to pass normally), the totally build time for both P and V is 82 minutes, down from ~287 minutes (4 hours, 47 minutes) when run without .ccache and running concurrently.  Ex: https://github.com/pkegg/351ELEC/runs/2751526066?check_suite_focus=true

This is probably low enough to already run `make clean` for all `main` builds, but if the toolchain can be cached, and full builds for P and V get below 50 minutes, it may make sense to run `make clean` for all PR builds as well.

**Comment by dhwz** [comment]
Oh wow good news

**Review by dhwz — APPROVED** [review]

**Review by Cebion — APPROVED** [review]

**Pull request merged**
