### PR TITLE
Cloud Save: support environment variables for remote name and path instead of hardcoding

### PR DESCRIPTION
**Pull request by codygarver**
The default Cloud Save values can be overridden by adding environment variables to profile.

351ELEC's default file works fine: `/storage/.config/profile.d/99-distribution_functions.conf`.

`CLOUD_SAVE_REMOTE` must match the remote name entry in `/storage/roms/gamedata/rclone/rclone.conf`. So if it contains `[my-s3-remote]`, the line would be `export CLOUD_SAVE_REMOTE="my-s3-remote"`

`CLOUD_SAVE_PATH` is where files should go on the remote. So if you're using an S3 bucket named `save-states`, the line would be `export CLOUD_SAVE_PATH="/save-states/"`

With only these modifications, the stock `99-distributons_functions.conf` would look like this:
```
# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2020-present Shanti Gilbert (https://github.com/shantigilbert)
# Copyright (C) 2020-present Fewtarius

# you can insert any functions you want to be loaded at boot here
export CLOUDSYNC_REMOTE_NAME="my-s3-remote"
export CLOUDSYNC_REMOTE_PATH="/save-states/"
```

### CODE REVIEW

**Comment by codygarver** [comment]
My S3 bucket has a different name. With this change I can just override the default names with a profile.d entry.

**Review by szalik-rg351 — APPROVED** [review]
1 approve for someone who will test

**Comment by pkegg** [comment]
@codygarver - I think this looks pretty good, I will try and test later today or tomorrow.  Can you document an example of your /etc/profile.d file?  

(Just edit the description of the PR or add a comment and paste in your example file, etc.  Nothing fancy needed, just want to make sure we capture that for easy future reference.)

**Comment by codygarver** [comment]
> @codygarver - I think this looks pretty good, I will try and test later today or tomorrow. Can you document an example of your /etc/profile.d file?
> 
> (Just edit the description of the PR or add a comment and paste in your example file, etc. Nothing fancy needed, just want to make sure we capture that for easy future reference.)

Description updated.

**Pull request closed without merging**
